<?php
/*
Plugin Name: Seoliz.com SEO Meta
Plugin URI: http://www.seoliz.com/wordpress-seoliz-com-seo-meta-eklentisi.htm
Description: Sitenizin yazılarına ve sayfalarına özel açıklamalar, anahtar kelimeler belirtebilirsiniz.
Version: 1.0
Author: İbrahim ÇAKICI
Author URI: http://www.seoliz.com/
*/
class SEOMeta {var $isim = 'SEOliz';var $etiket = 'lidyonseo';var $ayarlar = array();function SEOMeta(){if ($ayarlar = get_option($this->etiket)) {$this->options = $ayarlar;}add_action('wp_head', array(&$this, 'meta'));if (is_admin()) {add_action('admin_menu', array(&$this, 'YaziPanel'));add_action('save_post', array(&$this, 'Kaydet'));}}function Seometa_Etkinlestir(){if (!$this->options) {update_option($this->etiket, array('posts' => 1));}}function Seometa_Etkisizlestir(){if ($this->options) {update_option($this->etiket, null);}}function YaziPanel(){add_meta_box($this->etiket.'_postbox', "Seoliz.com SEO Meta", array(&$this, 'seoekran'), 'page', 'normal', 'high');if (isset($this->options['posts'])) {add_meta_box($this->etiket.'_postbox', "Seoliz.com SEO Meta", array(&$this, 'seoekran'), 'post', 'normal', 'high');}}function seoekran(){echo "<style type=\"text/css\">#seoliz_seometa {font-size: 12px;}#seoliz_seometa th {width: 120px;}#seoliz_seometa input {width: 100%;}</style>".wp_nonce_field(wp_.$this->etiket, $this->etiket.nonce)."<table id=\"seoliz_seometa\" class=\"form-table\"><tr><th><label>Açıklama</label></th><td><input type=\"text\" name=\"".$this->etiket."[description]\" value=\"".$this->alan('description')."\" /></td></tr><tr><th><label>Anahtar Kelimeler</label></th><td><input type=\"text\" name=\"".$this->etiket."[keywords]\" value=\"".$this->alan('keywords')."\" /></td></tr><tr><td><label>Sağlayıcı <a href=\"http://www.seoliz.com\">seoliz.com</a></label></td></tr></table>";}function Alan($alan){global $post;return get_post_meta($post->ID, '_'.$this->etiket.'_'.$alan, true);}function Kaydet($yazi_id){if (!isset($_POST[$this->etiket.'nonce']) || !wp_verify_nonce($_POST[$this->etiket.'nonce'], 'wp_'.$this->etiket)) {return $yazi_id;}if (!current_user_can('edit_page', $yazi_id)) {return $yazi_id;}foreach ($_POST[$this->etiket] AS $key => $deger) {$alan = '_'.$this->etiket.'_'.$key;$deger = wp_filter_kses($deger);if (empty($deger)) {delete_post_meta($yazi_id, $alan, $deger);} else if (!update_post_meta($yazi_id, $alan, $deger)) {add_post_meta($yazi_id, $alan, $deger);}}}function deger($type){global $wpdb;$p = get_query_var('p');$isim = get_query_var('isim');if (intval($p) || !empty($isim)) {if(!$p){$p = $wpdb->get_var($wpdb->prepare("SELECT ID FROM $wpdb->posts WHERE post_name = %s", $isim));}$post = &get_post($p);return get_post_meta($p, '_'.$this->etiket.'_'.$type, true);}}function meta(){$degerler = array('description', 'keywords');echo "<!-- Seoliz.com SEO Meta Eklentisi -->\r\n";foreach($degerler AS $isim){if($icerik = $this->deger($isim)){echo "<meta name=\"".$isim."\" content=\"".esc_attr($icerik)."\" />\r\n";}}}}$seometa = new SEOMeta();if(isset($seometa)){register_activation_hook(__FILE__, array(&$seometa, 'Seometa_Etkinlestir'));register_deactivation_hook(__FILE__, array(&$seometa, 'Seometa_Etkisizlestir'));}